@startuml

class AppConfig {
    - static volatile AppConfig instance
    - AppConfig()
    + static getInstance() : AppConfig
    + getConfigValue(key : String) : String
}

class SingletonTest {
    + main(args : String[]) : void
}


SingletonTest .down.> AppConfig : uses >
AppConfig <--o AppConfig

@enduml
